In [30]:
import os
import pandas as pd
import numpy as np

flu_csv = "flufighters/Deaths_from_Pneumonia_and_Influenza__P_I__and_all_deaths__by_state_and_region__National_Center_For_Health_Statistics_Mortality_Surveillance_System.csv"

flu_df = pd.read_csv(flu_csv)
flu_df.head(-10)

,geoid,Region,State,age,season,MMWR Year/Week,Deaths from influenza,Deaths from pneumonia,Deaths from pneumonia and influenza,All Deaths,Pecent of deaths due to pneumonia or influenza,pecent complete
0,National,NaN,NaN,All,2009-10,200940,149.0,3484.0,3633.0,46412.0,7.827717,97.546212
1,National,NaN,NaN,All,2009-10,200941,174.0,3703.0,3877.0,46453.0,8.346070,97.632384
2,National,NaN,NaN,All,2009-10,200942,239.0,3841.0,4080.0,47451.0,8.598344,99.729926
3,National,NaN,NaN,All,2009-10,200943,295.0,3762.0,4057.0,46432.0,8.737509,97.588247
4,National,NaN,NaN,All,2009-10,200944,298.0,3858.0,4156.0,47372.0,8.773115,99.563888
5,National,NaN,NaN,All,2009-10,200945,265.0,3929.0,4194.0,47314.0,8.864184,99.441987
6,National,NaN,NaN,All,2009-10,200946,208.0,3721.0,3929.0,46527.0,8.444559,97.787913
7,National,NaN,NaN,All,2009-10,200947,179.0,3655.0,3834.0,46422.0,8.259015,97.567230
8,National,NaN,NaN,All,2009-10,200948,126.0,3779.0,3905.0,47806.0,8.168431,100.476045
9,National,NaN,NaN,All,2009-10,200949,105.0,3982.0,4087.0,49304.0,8.289388,103.624460
10,National,NaN,NaN,All,2009-10,200950,84.0,3985.0,4069.0,49099.0,8.287338,103.193602
11,National,NaN,NaN,All,2009-10,200951,63.0,3838.0,3901.0,49105.0,7.944201,103.206213
12,National,NaN,NaN,All,2009-10,200952,47.0,4310.0,4357.0,49617.0,8.781264,104.282306
13,National,NaN,NaN,All,2009-10,201001,37.0,4428.0,4465.0,51018.0,8.751813,107.226852
14,National,NaN,NaN,All,2009-10,201002,39.0,4471.0,4510.0,51275.0,8.795709,107.767000
15,National,NaN,NaN,All,2009-10,201003,28.0,4314.0,4342.0,49912.0,8.699311,104.902321
16,National,NaN,NaN,All,2009-10,201004,29.0,4072.0,4101.0,48443.0,8.465619,101.814857
17,National,NaN,NaN,All,2009-10,201005,27.0,4085.0,4112.0,49079.0,8.378329,103.151567
18,National,NaN,NaN,All,2009-10,201006,38.0,4128.0,4166.0,50120.0,8.312051,105.339484
19,National,NaN,NaN,All,2009-10,201007,23.0,4236.0,4259.0,50484.0,8.436336,106.104520
20,National,NaN,NaN,All,2009-10,201008,30.0,4291.0,4321.0,50193.0,8.608770,105.492912
21,National,NaN,NaN,All,2009-10,201009,28.0,4342.0,4370.0,50345.0,8.680107,105.812377
22,National,NaN,NaN,All,2009-10,201010,30.0,4377.0,4407.0,50219.0,8.775563,105.547557
23,National,NaN,NaN,All,2009-10,201011,29.0,4236.0,4265.0,49270.0,8.656383,103.553001
24,National,NaN,NaN,All,2009-10,201012,25.0,4081.0,4106.0,48294.0,8.502091,101.501697
25,National,NaN,NaN,All,2009-10,201013,28.0,3986.0,4014.0,48795.0,8.226253,102.554672
26,National,NaN,NaN,All,2009-10,201014,14.0,3983.0,3997.0,47769.0,8.367351,100.398281
27,National,NaN,NaN,All,2009-10,201015,13.0,3730.0,3743.0,47102.0,7.946584,98.996417
28,National,NaN,NaN,All,2009-10,201016,9.0,3569.0,3578.0,46620.0,7.674818,97.983375
29,National,NaN,NaN,All,2009-10,201017,7.0,3605.0,3612.0,46319.0,7.798096,97.350750
...,...,...,...,...,...,...,...,...,...,...,...,...
31378,State,NaN,Idaho,All,2018-19,201846,NaN,NaN,12.0,238.0,5.042017,107.066446
31379,State,NaN,Illinois,All,2018-19,201846,NaN,NaN,96.0,1866.0,5.144695,96.669079
31380,State,NaN,Indiana,All,2018-19,201846,NaN,NaN,48.0,906.0,5.298013,82.604732
31381,State,NaN,Iowa,All,2018-19,201846,NaN,NaN,29.0,460.0,6.304348,86.180159
31382,State,NaN,Kansas,All,2018-19,201846,NaN,NaN,29.0,433.0,6.697460,91.833173
31383,State,NaN,Kentucky,All,2018-19,201846,NaN,NaN,19.0,335.0,5.671642,41.348255
31384,State,NaN,Louisiana,All,2018-19,201846,NaN,NaN,7.0,328.0,2.134146,41.930137
31385,State,NaN,Maine,All,2018-19,201846,NaN,NaN,19.0,267.0,7.116105,109.197112
31386,State,NaN,Maryland,All,2018-19,201846,NaN,NaN,53.0,784.0,6.760204,94.112241
31387,State,NaN,Massachusetts,All,2018-19,201846,NaN,NaN,66.0,1019.0,6.476938,100.916427
31388,State,NaN,Michigan,All,2018-19,201846,NaN,NaN,93.0,1628.0,5.712531,96.421993
31389,State,NaN,Minnesota,All,2018-19,201846,NaN,NaN,42.0,769.0,5.461638,102.932587
31390,State,NaN,Mississippi,All,2018-19,201846,NaN,NaN,22.0,345.0,6.376812,62.258775
31391,State,NaN,Missouri,All,2018-19,201846,NaN,NaN,41.0,715.0,5.734266,67.744246
31392,State,NaN,Montana,All,2018-19,201846,NaN,NaN,4.0,53.0,7.547170,31.542229
31393,State,NaN,Nebraska,All,2018-19,201846,NaN,NaN,19.0,268.0,7.089552,91.779318
31394,State,NaN,Nevada,All,2018-19,201846,NaN,NaN,29.0,382.0,7.591623,100.017539
31395,State,NaN,New Hampshire,All,2018-19,201846,NaN,NaN,13.0,216.0,6.018519,108.209689
31396,State,NaN,New Jersey,All,2018-19,201846,NaN,NaN,81.0,1277.0,6.342991,95.890160
31397,State,NaN,New Mexico,All,2018-19,201846,NaN,NaN,10.0,233.0,4.291845,75.361354
31398,State,NaN,New York,All,2018-19,201846,NaN,NaN,122.0,1139.0,10.711150,62.477134
31399,State,NaN,New York City,All,2018-19,201846,NaN,NaN,NaN,NaN,NaN,9.239611
31400,State,NaN,North Carolina,All,2018-19,201846,NaN,NaN,NaN,NaN,NaN,2.307629
31401,State,NaN,North Dakota,All,2018-19,201846,NaN,NaN,1.0,78.0,1.282051,68.527471
31402,State,NaN,Ohio,All,2018-19,201846,NaN,NaN,10.0,604.0,1.655629,29.346222
31403,State,NaN,Oklahoma,All,2018-19,201846,NaN,NaN,34.0,477.0,7.127883,68.506697
31404,State,NaN,Oregon,All,2018-19,201846,NaN,NaN,17.0,317.0,5.362776,51.454245
31405,State,NaN,Pennsylvania,All,2018-19,201846,NaN,NaN,80.0,1485.0,5.387205,61.635022
31406,State,NaN,Rhode Island,All,2018-19,201846,NaN,NaN,NaN,NaN,NaN,7.735829
31407,State,NaN,South Carolina,All,2018-19,201846,NaN,NaN,44.0,845.0,5.207101,105.996495

In [38]:
flu_column_subset = pd.DataFrame(flu_df, columns = ["State", "season", "MMWR Year/Week", "Deaths from influenza", "Deaths from pneumonia", "All Deaths"])


flu_column_subset.head()
flu_column_subset["season"].count()

31418

In [60]:
# flu2017 = flu_column_subset[flu_column_subset['MMWR Year/Week]
flu_column_subset['MMWR Year/Week'] = flu_column_subset['MMWR Year/Week'].astype(str)
flu_column_subset['Year'] = flu_column_subset['MMWR Year/Week'].str[:4]
flu_column_subset['Week'] = flu_column_subset['MMWR Year/Week'].str[4:]

flu_final = pd.DataFrame(flu_column_subset, columns = ["State", "Deaths from influenza", "Deaths from pneumonia", "All Deaths", "Year", "Week"])
# flu_final.loc[flu_final['State'] != "NaN"]
# flu_final = flu_final[np.isfinite(flu_final['State'])]
# flu_final["State"].count()
flu_final = flu_final[flu_final.State!=None]
flu_final.head()

  State  Deaths from influenza  Deaths from pneumonia  All Deaths  Year Week
0   NaN                  149.0                 3484.0     46412.0  2009   40
1   NaN                  174.0                 3703.0     46453.0  2009   41
2   NaN                  239.0                 3841.0     47451.0  2009   42
3   NaN                  295.0                 3762.0     46432.0  2009   43
4   NaN                  298.0                 3858.0     47372.0  2009   44

In [49]:
flu_final.head()

  State  Deaths from influenza  Deaths from pneumonia  All Deaths  Year Week
0   NaN                  149.0                 3484.0     46412.0  2009   40
1   NaN                  174.0                 3703.0     46453.0  2009   41
2   NaN                  239.0                 3841.0     47451.0  2009   42
3   NaN                  295.0                 3762.0     46432.0  2009   43
4   NaN                  298.0                 3858.0     47372.0  2009   44

In [53]:
flu_final.dtypes

State                     object
Deaths from influenza    float64
Deaths from pneumonia    float64
All Deaths               float64
Year                      object
Week                      object
dtype: object

In [59]:
print(flu_final.State[0])

nan