In [1]:
# Dependencies
import pandas as pd

# Store filepath in a variable
file_one = "state_population_data.txt"

# Read our Data file with the pandas library
# Not every CSV requires an encoding, but be aware this can come up
file_one_df = pd.read_csv(file_one, encoding="ISO-8859-1")


# Show just the header
file_one_df.head()

,"Rank in the fifty states, 2016","Rank in all states & territories, 2010",State or territory,Population estimate 2016,"Census population, April 1, 2010","Total seats in House of Representatives, 20132023","Estimated pop. per House seat, 2016","Census pop. per House seat, 2010",Percent of total U.S. population 2016
0,1,1,California,"39,250,017","37,254,503",53,"738,581","702,905",12.15%
1,2,2,Texas,"27,862,596","25,146,105",36,"763,031","698,487",8.62%
2,4,3,New York,"19,745,289","19,378,087",27,"733,177","717,707",6.11%
3,3,4,Florida,"20,612,439","18,804,623",27,"750,788","696,345",6.38%
4,5,5,Illinois,"12,801,539","12,831,549",18,"714,444","712,813",3.96%

In [2]:
three_field = file_one_df[["State or territory" , "Population estimate 2016" , "Percent of total U.S. population 2016"]].head(100)
three_field.head()

,State or territory,Population estimate 2016,Percent of total U.S. population 2016
0,California,"39,250,017",12.15%
1,Texas,"27,862,596",8.62%
2,New York,"19,745,289",6.11%
3,Florida,"20,612,439",6.38%
4,Illinois,"12,801,539",3.96%

In [3]:
three_field.to_csv("StateTerritory_population_v1.csv", index=False, header=True)